highlighter: rouge
permalink: /posts/:title.html

title: Journey to the West
author:
  name: acgtun
  email: acgtun at gmail dot com
  github: acgtun

production_url: http://blog.acgtun.com

baseurl: /

comments: true
markdown: kramdown

plugins:
  - jekyll-seo-tag
